name: A pipeline for testing, building and deploying YTR service data importer function

resources:
- repo: self

trigger:
  branches:
    include:
    - nobranch
  paths:
    exclude:
    - README.md
    - docker-compose.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
  isProd: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isTest: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]

  azureContainerRegistryTest: tkupaohtestcontainerregistry.azurecr.io
  azureContainerRegistryProd: tkupaohtuotcontainerregistry.azurecr.io
  azureSubscriptionEndpointTest: tku-palveluohjain-testi-sc
  azureSubscriptionEndpointProd: tku-palveluohjain-tuotanto-sc
  azureSubscriptionEndpointIntra: tku-palveluohjain-intra-sc
  kubernetesServiceConnectionTest: tku-palveluohjain-testi-aks-sc
  kubernetesServiceConnectionProd: tku-palveluohjain-tuotanto-aks-sc
  dockerRegistryEndpointTest: tku-palveluohjain-testi-docker-sc
  dockerRegistryEndpointProd: tku-palveluohjain-tuotanto-docker-sc
  azurestorageaccountnameTest: tkupaohteststorage
  azurestorageaccountnameProd: tkupaohprodstorage
  intraResourceGroup: tku-palveluohjain-intra

  ytrServiceDataImportImage: <COMES FROM KUBE>


stages:
- stage: Test
  displayName: Run tests
  jobs:
  - job: UnitTests
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: '3.8'

    - script: python3 -m pip install --upgrade pip setuptools wheel
      displayName: 'Install tools'

    - script: pip install -r ytr_service_data_import/requirements.txt
      displayName: 'Installing YTR Service Data Import requirements'

    - script: python3 -m unittest discover -s test --verbose
      displayName: 'Run tests'

- stage: BuildTest
  displayName: Build image for test environment
  condition: and(eq(variables.isTest, true), succeeded())
  variables:
    - group: tku-paoh-test-variable-group
  dependsOn: Test
  jobs:
  - job: Build
    displayName: Build
    steps:

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryEndpointTest)

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: ytrservicedataimport
        containerRegistry: $(dockerRegistryEndpointTest)
        dockerfile: '$(Build.SourcesDirectory)/ytr_service_data_import/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push image to the container registry
      inputs:
        command: push
        repository: ytrservicedataimport
        containerRegistry: $(dockerRegistryEndpointTest)
        tags: |
          $(tag)

- stage: BuildProd
  displayName: Build image for prod environment
  condition: and(eq(variables.isProd, true), succeeded())
  variables:
    - group: tku-paoh-tuot-variable-group
  dependsOn: Test
  jobs:
  - job: Build
    displayName: Build
    steps:

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryEndpointProd)

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: ytrservicedataimport
        containerRegistry: $(dockerRegistryEndpointProd)
        dockerfile: '$(Build.SourcesDirectory)/ytr_service_data_import/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push image to the container registry
      inputs:
        command: push
        repository: ytrservicedataimport
        containerRegistry: $(dockerRegistryEndpointProd)
        tags: |
          $(tag)


- stage: DeployTest
  condition: and(eq(variables.isTest, true), succeeded())
  dependsOn: BuildTest
  displayName: Deploy to test environment to Azure
  variables:
    - group: tku-paoh-test-variable-group
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:

    - task: replacetokens@3
      displayName: 'Replace tokens in .yaml files'
      inputs:
        targetFiles: |
          $(Build.SourcesDirectory)/aci/*.yaml
        verbosity: detailed
        tokenPrefix: '__'
        tokenSuffix: '__'

    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container Instance'
      inputs:
        azureSubscription: $(azureSubscriptionEndpointIntra)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: az container create --resource-group $(intraResourceGroup) --file $(Build.SourcesDirectory)/aci/ytr-service-data-import.yaml
 

- stage: DeployProd
  condition: and(eq(variables.isProd, true), succeeded())
  dependsOn: BuildProd
  displayName: Deploy to production environment to Azure
  variables:
    - group: tku-paoh-tuot-variable-group
  jobs:
  - job: Deploy
    displayName: Deploy
    steps: 

    - task: replacetokens@3
      displayName: 'Replace tokens in .yaml files'
      inputs:
        targetFiles: |
          $(Build.SourcesDirectory)/aci/*.yaml
        verbosity: detailed
        tokenPrefix: '__'
        tokenSuffix: '__'

    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container Instance'
      inputs:
        azureSubscription: $(azureSubscriptionEndpointIntra)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: az container create --resource-group $(intraResourceGroup) --file $(Build.SourcesDirectory)/aci/ytr-service-data-import.yaml
